### ISSUE TITLE
Returning intermediate ccv types to python

### ISSUE THREAD

**Issue by mpcuter** [marrrcin/swt-python#3]
Hi, 

Thanks for sharing! I ran your code successfully. I'd like to get access to raw SWT matrix its type is ' ccv_dense_matrix_t* '. What changes do I need to make in order to return this type to python?

Thanks!
Mike

Below is a code snippet of what I am trying to achieve. 

ccv_dense_matrix_t* swt(char *bytes, int array_length, int width, int height){
        int *result_array;
        int status = FAILURE;
       ccv_enable_default_cache();
	ccv_dense_matrix_t* image = 0;
       ccv_dense_matrix_t* swtImage = 0;
	FILE *stream;
	stream = fmemopen(bytes, array_length, "r");
	if(stream != NULL){
        int type = CCV_IO_JPEG_FILE | CCV_IO_GRAY;
        int ctype = (type & 0xF00) ? CCV_8U | ((type & 0xF00) >> 8) : 0;
        _ccv_read_jpeg_fd(stream, &image, ctype);

        if (image != 0)
        {
            ccv_swt(image, &swtImage, 0, ccv_swt_default_params);
            ccv_matrix_free(image);
        }
        ccv_drain_cache();
	}
    if(status != SUCCESS){
        result_array = (int*)malloc(1 * sizeof(int));
        result_array[0] = 0;
    }
    return swtImage;
}

**Comment by marrrcin** [comment]
You need to map this type to something similar in Python i.e nested lists.
