### ISSUE TITLE
where is ccv_*

### ISSUE THREAD

**Issue by 852591766** [marrrcin/swt-python#4]
I want to run gcc -fpic -c ccvwrapper.c ccvwrapper_wrap.c ccv_algebra.c ccv_basic.c ccv_cache.c ccv_classic.c ccv_io.c ccv_memory.c ccv_output.c ccv_resample.c ccv_sift.c ccv_swt.c ccv_transform.c ccv_util.c ./3rdparty/sha1/sha1.c -I/usr/include/python2.7
but there is not ccv_algebra.c ccv_basic.c ccv_cache.c ccv_classic.c ccv_io.c ccv_memory.c ccv_output.c ccv_resample.c ccv_sift.c ccv_swt.c ccv_transform.c

**Comment by ghost** [comment]
Refer to the ccv repository here: https://github.com/liuliu/ccv
