### ISSUE TITLE
Is there a version to get this running on OSX?

### ISSUE THREAD

**Issue by sizhky** [marrrcin/swt-python#5]
I'm unable to replicate the steps as there are a bunch of errors when following these steps

**Comment by marrrcin** [comment]
I will be updating this repo with Python 3.5+ compatible version with macOS support next week.

**Comment by jtlz2** [comment]
@marrrcin Awesome - any update on this?

**Comment by jtlz2** [comment]
@sizhky Did you ever get it working?
